// Configuration FontAwesome SIMPLE et ROBUSTE
import { library } from "@fortawesome/fontawesome-svg-core";

// Import DES icônes (sans doublons)
import {
  faArrowLeft,
  faCircleCheck,
  faTriangleExclamation,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faCalendarDays,
  faUser,
  faPhone,
  faLocationDot,
  faHouseChimney,
  faHashtag,
  faCity,
  faGear,
  faArrowUp,
  faHeart,
  faShoppingCart,
  faSearch,
  faBars,
  faSignOutAlt,
  faShieldAlt,
  faKey,
  faDownload,
  faTrashAlt,
  faEdit,
  faSave,
  faCamera,
  faRedo,
  faCreditCard,
} from "@fortawesome/free-solid-svg-icons";

import {
  faInstagram,
  faFacebook,
  faPinterest,
  faCcVisa,
  faCcMastercard,
  faCcAmex,
  faCcPaypal,
} from "@fortawesome/free-brands-svg-icons";

// Ajouter TOUTES les icônes une seule fois
library.add(
  faArrowLeft,
  faCircleCheck,
  faTriangleExclamation,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faCalendarDays,
  faUser,
  faPhone,
  faLocationDot,
  faHouseChimney,
  faHashtag,
  faCity,
  faGear,
  faArrowUp,
  faHeart,
  faShoppingCart,
  faSearch,
  faBars,
  faSignOutAlt,
  faShieldAlt,
  faKey,
  faDownload,
  faTrashAlt,
  faEdit,
  faSave,
  faCamera,
  faRedo,
  faCreditCard,
  faInstagram,
  faFacebook,
  faPinterest,
  faCcVisa,
  faCcMastercard,
  faCcAmex,
  faCcPaypal
);

export default library;
